In [ ]:
import numpy as np
import random

Creating numpy arrays

In [ ]:
#Creating an array with random integers
arr1=np.random.randint(1,100,10)

In [ ]:
arr1

array([77, 98, 37, 89, 11,  4, 18, 22, 81, 25])

In [ ]:
#Creating an array with random integers
arr2=np.random.randint(1,500,10)

In [ ]:
arr2

array([339, 168, 464, 270, 128, 200,  72, 353, 480, 265])

Basic Operations on arrays

In [ ]:
#Return no.of dimensions(axes) of the array
arr1.ndim

1

In [ ]:
#Returns the tuple of integers indicating the size of array in each dimension
arr1.shape

(10,)

In [ ]:
#Returns the size of the array
arr1.size

10

In [ ]:
#Returs the data type of the array
arr1.dtype

dtype('int32')

In [ ]:
#Return the size of each element in the array
arr1.itemsize

4

In [ ]:
#return the total number of bytes for all elements in the array
arr1.nbytes

40

Data manipulation

In [ ]:
#indexing
arr1[2]

83

In [ ]:
arr2[4]

60

In [ ]:
#Slicing

In [ ]:
arr1[1:4]

array([25, 83, 86])

In [ ]:
arr2[1:6]

array([268, 274, 173,  60,  87])

In [ ]:
#Creating a 2d array using replalce
arr2d=np.arange(0,20,2).reshape(2,5)

In [ ]:
arr2d

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [ ]:
#indexing a 2d array the : left side represents the rows and right side represents the columns
arr2d[:1]

array([[0, 2, 4, 6, 8]])

In [ ]:
arr2d1=np.arange(0,40,4).reshape(2,5)

In [ ]:
arr2d1

array([[ 0,  4,  8, 12, 16],
       [20, 24, 28, 32, 36]])

In [ ]:
T_arr=arr2d1.T

Mathematical Operations

In [ ]:
#Addition
arr1+arr2

array([ 71, 293, 357, 259, 128,  88,  53, 399,  89,  32])

In [ ]:
#Subtraction
arr2-arr1

array([  3, 243, 191,  87,  -8,  86,  25, 235, -29,  22])

In [ ]:
#multiplication
arr1*arr2

array([ 1258,  6700, 22742, 14878,  4080,    87,   546, 25994,  1770,
         135])

In [ ]:
#division
arr2/arr1

array([ 1.08823529, 10.72      ,  3.30120482,  2.01162791,  0.88235294,
       87.        ,  2.78571429,  3.86585366,  0.50847458,  5.4       ])

In [ ]:
arr2 ** 2

array([  1369,  71824,  75076,  29929,   3600,   7569,   1521, 100489,
          900,    729])

Matrix operation

In [ ]:
#Matrix multiplication (Dot Product)
np.dot(arr2d,T_arr)

array([[ 240,  640],
       [ 640, 2040]])

In [ ]:
#Matrix Multiplication
arr2d*arr2d1

array([[  0,   8,  32,  72, 128],
       [200, 288, 392, 512, 648]])

In [ ]:
#Matrix Additio
arr2d+arr2d1

array([[ 0,  6, 12, 18, 24],
       [30, 36, 42, 48, 54]])

In [ ]:
#Matrix Subtraction
arr2d1-arr2d

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [ ]:
#Matrix Division
arr2d1/arr2d

array([[nan,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

Numpy Aggregation Functions

In [ ]:
#Sum function in numpy arrays
print("Sum of all elements in the array")
print(np.sum(arr1))
#Sum along the axis
print("Sum along the 0th axis")
print(np.sum(arr2d,axis=0))
print("Sum along the 1st axis")
print(np.sum(arr2d,axis=1))

Sum of all elements in the array
395
Sum along the 0th axis
[10 14 18 22 26]
Sum along the 1st axis
[20 70]


In [ ]:
#Min value in the array
print("Min value of the array")
print(np.min(arr1))
#Max value of the array
print("Max value of the array")
print(np.max(arr1))


Min value of the array
4
Max value of the array
82


In [ ]:
#Mean of the array
print("Mean value of the array")
print(np.mean(arr1))


Mean value of the array
39.5


In [ ]:
#Median of the array
print("Median value of the array")
print(np.median(arr1))

Median value of the array
36.0


In [ ]:
#Standard Deviation of the array
print("Standard Deviation of the array")
print(np.std(arr1))

Standard Deviation of the array
31.987653868328636


In [ ]:
#Variance of the array
print("Variance of the array")
print(np.var(arr1))

Variance of the array
757.65


In [ ]:
#Productof the array
print("Product of the array")
print(np.prod(arr1))

Product of the array
411890432


In [ ]:
#Cumulative Sum of the array
print("Cumulative Sum of the array")
print(np.cumsum(arr1))

Cumulative Sum of the array
[ 42 124 154 177 187 248 299 303 385 395]


In [ ]:
#Cumulative Product of the array
print("Cumulative Product of the array")
print(np.cumprod(arr1))

Cumulative Product of the array
[        42       3444     103320    2376360   23763600 1449579600
  914115568 -638505024 -817804416  411890432]


In [ ]:
#Percentile of the array
print("Percentile of the array")
np.percentile(arr1,50)

Percentile of the array


36.0

Data Analysis using numpy

In [ ]:
#Generating two large datasets
data1=np.random.rand(1000000)
data2=0.1*data1 + np.random.rand(1000000)*0.1


In [ ]:
data1

array([0.31869265, 0.98678722, 0.68401622, ..., 0.26870889, 0.31653988,
       0.08508693])

In [ ]:
data2

array([0.12017988, 0.12562   , 0.16340455, ..., 0.04953158, 0.05296569,
       0.03282584])

In [ ]:
#Co-relation of the datas
co_mat=np.corrcoef(data1,data2)
co_mat[0,1]

0.7070486239491695

In [ ]:
#Calculating Percentiles
data=np.random.randn(1000000)

percentiles=np.percentile(data,[25,50,75])

In [ ]:
percentiles

array([-6.73489274e-01, -2.56438795e-04,  6.73844579e-01])